# Generated by Django 4.1.7 on 2023-03-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_remove_vacations_employee'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vacations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vacations.vacations'),
        ),
    ]
