# Generated by Django 4.1.7 on 2023-03-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_vacations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='vacations',
        ),
    ]
