# Generated by Django 4.1.3 on 2023-04-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_employee_vacations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[("W", "Working"), ("V", "On Vacation")],
                default="W",
                max_length=1,
            ),
        ),
    ]
