# Generated by Django 4.1.3 on 2023-04-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_employee_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[("working", "Working"), ("on vacation", "On Vacation")],
                default="working",
                max_length=12,
            ),
        ),
    ]
