# Generated by Django 4.1.7 on 2023-03-23 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True)),
                ('requests_date', models.DateTimeField(auto_now=True)),
                ('date_of_begin', models.DateField()),
                ('date_of_end', models.DateField()),
                ('send_to_all', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
