# Generated by Django 4.1.3 on 2023-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0003_vacations_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacations",
            name="accepted",
        ),
        migrations.RemoveField(
            model_name="vacations",
            name="send_to_all",
        ),
        migrations.AddField(
            model_name="vacations",
            name="count_of_Vacations",
            field=models.IntegerField(default=0),
        ),
    ]
