# Generated by Django 4.1.3 on 2023-04-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0004_remove_vacations_accepted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacations",
            old_name="count_of_Vacations",
            new_name="count_of_vacations",
        ),
        migrations.AddField(
            model_name="vacations",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vacations",
            name="send_to_all",
            field=models.BooleanField(default=False),
        ),
    ]
