# Generated by Django 4.1.3 on 2023-04-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vacations",
            "0005_rename_count_of_vacations_vacations_count_of_vacations_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacations",
            name="status",
            field=models.CharField(
                choices=[("planed", "Planed"), ("now", "Now")],
                default="planed",
                max_length=10,
            ),
        ),
    ]
